// copy/src/features/classes/components/CreateClassModal.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { ClassCreateRequest, ClassUpdateRequest, CLASS_LEVELS } from '../types/classes';

interface CreateClassModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: ClassCreateRequest | ClassUpdateRequest) => void;
  loading: boolean;
  editData?: any;
}

const CreateClassModal: React.FC<CreateClassModalProps> = ({
  isOpen,
  onClose,
  onSubmit,
  loading,
  editData,
}) => {
  const { t } = useTranslation();
  const [formData, setFormData] = useState<ClassCreateRequest>({
    name: editData?.name || '',
    code: editData?.code || '',
    level: editData?.level || 1,
    capacity: editData?.capacity || 30,
    expectedFees: editData?.expectedFees || 0,
    shift: editData?.shift || 'morning',
    gender: editData?.gender || 'boys',
    schoolId: 1, // Default school ID
    createdBy: 1, // Default user ID - should be dynamic based on authenticated user
  });

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isGeneratingCode, setIsGeneratingCode] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState<string>('');
  const [showAutoGenerated, setShowAutoGenerated] = useState(false);

  // Auto-generate class code when class name changes
  const generateClassCode = useCallback(async (className: string) => {
    if (!className.trim()) {
      setAutoGeneratedCode('');
      setShowAutoGenerated(false);
      return;
    }

    setIsGeneratingCode(true);
    try {
      // Simple auto-generation logic - can be enhanced with API call
      const level = formData.level || 1;
      const generatedCode = `C${level}`;
      
      setAutoGeneratedCode(generatedCode);
      setShowAutoGenerated(true);
      
      // Auto-fill the code field if it's empty
      if (!formData.code || formData.code === formData.name) {
        setFormData(prev => ({ ...prev, code: generatedCode }));
      }
    } catch (error) {
      console.error('Error generating class code:', error);
      // Fallback to simple generation
      const fallbackCode = `C${formData.level || 1}`;
      setAutoGeneratedCode(fallbackCode);
      setShowAutoGenerated(true);
      
      if (!formData.code || formData.code === formData.name) {
        setFormData(prev => ({ ...prev, code: fallbackCode }));
      }
    } finally {
      setIsGeneratingCode(false);
    }
  }, [formData.level, formData.code, formData.name]);

  // Reset form when modal opens/closes
  useEffect(() => {
    if (isOpen) {
      resetForm();
    }
  }, [isOpen]);

  // Debounced effect to generate code when class name changes
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      if (formData.name.trim()) {
        generateClassCode(formData.name);
      }
    }, 500); // 500ms delay to avoid excessive calls

    return () => clearTimeout(timeoutId);
  }, [formData.name, generateClassCode]);

  const handleInputChange = (field: keyof ClassCreateRequest, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    // Clear error when user starts typing
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: '' }));
    }
    
    // Hide auto-generated suggestion when user manually types code
    if (field === 'code') {
      setShowAutoGenerated(false);
    }
  };

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    // Name validation
    if (!formData.name.trim()) {
      newErrors.name = t('classes.createClass.errors.nameRequired');
    } else if (formData.name.length > 100) {
      newErrors.name = t('classes.createClass.errors.nameTooLong');
    }

    // Code validation
    if (!formData.code.trim()) {
      newErrors.code = t('classes.createClass.errors.codeRequired');
    } else if (formData.code.length > 20) {
      newErrors.code = t('classes.createClass.errors.codeTooLong');
    }

    // Level validation
    if (!formData.level || formData.level < 1 || formData.level > 20) {
      newErrors.level = t('classes.createClass.errors.levelRange');
    }

    // Capacity validation
    if (!formData.capacity || formData.capacity < 1 || formData.capacity > 1000) {
      newErrors.capacity = t('classes.createClass.errors.capacityRange');
    }

    // SchoolId validation
    if (!formData.schoolId || formData.schoolId < 1) {
      newErrors.schoolId = t('classes.createClass.errors.schoolIdRequired');
    }

    // CreatedBy validation
    if (!formData.createdBy || formData.createdBy < 1) {
      newErrors.createdBy = t('classes.createClass.errors.userIdRequired');
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Reset form to initial state
  const resetForm = () => {
    setFormData({
      name: editData?.name || '',
      code: editData?.code || '',
      level: editData?.level || 1,
      capacity: editData?.capacity || 30,
      expectedFees: editData?.expectedFees || 0,
      shift: editData?.shift || 'morning',
      gender: editData?.gender || 'boys',
      schoolId: 1,
      createdBy: 1,
    });
    setErrors({});
    setAutoGeneratedCode('');
    setShowAutoGenerated(false);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (validateForm()) {
      // Add updatedBy field for updates
      const submitData = editData 
        ? { ...formData, updatedBy: 1 } // Default user ID - should be dynamic based on authenticated user
        : formData;
      onSubmit(submitData);
    }
  };

  const handleClose = () => {
    if (!loading) {
      resetForm();
      onClose();
    }
  };

  const handleGenerateCode = async () => {
    if (formData.name.trim()) {
      await generateClassCode(formData.name);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
      <div className="relative top-20 mx-auto p-5 border w-11/12 md:w-2/3 lg:w-1/2 shadow-lg rounded-md bg-white">
        <div className="mt-3">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-lg font-medium text-gray-900 flex items-center gap-2">
              <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
              </svg>
              {editData ? t('classes.createClass.editTitle') : t('classes.createClass.createTitle')}
            </h3>
            <button
              onClick={handleClose}
              className="text-gray-400 hover:text-gray-600 transition-colors duration-200"
            >
              <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Class Name */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                  <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                  </svg>
                  {t('classes.createClass.fields.className')} *
                </label>
                <div className="relative">
                  <input
                    type="text"
                    value={formData.name}
                    onChange={(e) => handleInputChange('name', e.target.value)}
                    className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                      errors.name ? 'border-red-300' : 'border-gray-300'
                    }`}
                    placeholder={t('classes.createClass.placeholders.className')}
                    disabled={loading}
                  />
                  {isGeneratingCode && (
                    <div className="absolute right-3 top-2.5">
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-500"></div>
                    </div>
                  )}
                </div>
                {formData.name.trim() && (
                  <p className="mt-1 text-xs text-gray-500">
                    {isGeneratingCode 
                      ? t('classes.createClass.generatingCode') 
                      : t('classes.createClass.autoGeneratedInfo')
                    }
                  </p>
                )}
                {errors.name && <p className="mt-1 text-sm text-red-600">{errors.name}</p>}
              </div>

              {/* Class Code */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                  <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                  {t('classes.createClass.fields.classCode')} *
                </label>
                <div className="space-y-2">
                  <div className="flex space-x-2">
                    <input
                      type="text"
                      value={formData.code}
                      onChange={(e) => {
                        const upperCaseValue = e.target.value.toUpperCase();
                        handleInputChange('code', upperCaseValue);
                      }}
                      className={`flex-1 px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                        errors.code ? 'border-red-300' : 'border-gray-300'
                      }`}
                      placeholder={t('classes.createClass.placeholders.classCode')}
                      disabled={loading}
                    />
                    <button
                      type="button"
                      onClick={handleGenerateCode}
                      disabled={loading || isGeneratingCode}
                      className="px-3 py-2 text-sm font-medium text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {isGeneratingCode ? (
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-500"></div>
                      ) : (
                        <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                        </svg>
                      )}
                    </button>
                  </div>
                  
                  {/* Auto-generated code suggestion */}
                  {showAutoGenerated && autoGeneratedCode && (
                    <div className="flex items-center space-x-2 bg-blue-50 p-3 rounded-lg border border-blue-200">
                      <svg className="h-4 w-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                      </svg>
                      <span className="text-sm text-blue-700 flex-1">
                        {t('classes.createClass.suggestedCode')}: <span className="font-semibold">{autoGeneratedCode}</span>
                      </span>
                      <button
                        type="button"
                        onClick={() => {
                          setFormData(prev => ({ ...prev, code: autoGeneratedCode }));
                          setShowAutoGenerated(false);
                        }}
                        className="px-2 py-1 text-xs font-medium text-blue-600 bg-white border border-blue-200 rounded hover:bg-blue-50"
                      >
                        {t('classes.createClass.use')}
                      </button>
                    </div>
                  )}
                  
                  <p className="text-xs text-gray-500">
                    {t('classes.createClass.codeDescription')}
                  </p>
                </div>
                {errors.code && <p className="mt-1 text-sm text-red-600">{errors.code}</p>}
              </div>

              {/* Level */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                  <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14" />
                  </svg>
                  {t('classes.createClass.fields.level')} *
                </label>
                <select
                  value={formData.level}
                  onChange={(e) => handleInputChange('level', parseInt(e.target.value))}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                    errors.level ? 'border-red-300' : 'border-gray-300'
                  }`}
                >
                  {CLASS_LEVELS.map(level => (
                    <option key={level} value={level}>{t('classes.level')} {level}</option>
                  ))}
                </select>
                {errors.level && <p className="mt-1 text-sm text-red-600">{errors.level}</p>}
              </div>



              {/* Capacity */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                  <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
                  </svg>
                  {t('classes.createClass.fields.capacity')} *
                </label>
                <input
                  type="number"
                  min="1"
                  value={formData.capacity}
                  onChange={(e) => handleInputChange('capacity', parseInt(e.target.value))}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 ${
                    errors.capacity ? 'border-red-300' : 'border-gray-300'
                  }`}
                  placeholder={t('classes.createClass.placeholders.capacity')}
                />
                {errors.capacity && <p className="mt-1 text-sm text-red-600">{errors.capacity}</p>}
              </div>

              {/* Expected Fees */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                  <svg className="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  {t('classes.expectedFee')}
                </label>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={formData.expectedFees}
                  onChange={(e) => handleInputChange('expectedFees', parseFloat(e.target.value) || 0)}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 ${
                    errors.expectedFees ? 'border-red-300' : 'border-gray-300'
                  }`}
                  placeholder= {t('classes.expectedFeePlaceHolder')}
                />
                <p className="mt-1 text-xs text-gray-500">
                  💡 {t('classes.expectedFeeDesc')}
                </p>
                {errors.expectedFees && <p className="mt-1 text-sm text-red-600">{errors.expectedFees}</p>}
              </div>

              {/* Shift */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                  <svg className="w-5 h-5 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                  </svg>
                  {t('classes.shift')}
                </label>
                <select
                  value={formData.shift}
                  onChange={(e) => handleInputChange('shift', e.target.value as 'morning' | 'afternoon')}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500 ${
                    errors.shift ? 'border-red-300' : 'border-gray-300'
                  }`}
                >
                  <option value="morning">☀️ {t('classes.morning')}</option>
                  <option value="afternoon">🌙 {t('classes.afternoon')}</option>
                </select>
                <p className="mt-1 text-xs text-gray-500">
                  {t('classes.shiftSelect')}
                </p>
                {errors.shift && <p className="mt-1 text-sm text-red-600">{errors.shift}</p>}
              </div>

              {/* Gender */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2 flex items-center gap-2">
                  <svg className="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                  </svg>
                  {t('classes.genderCtg')}
                </label>
                <select
                  value={formData.gender}
                  onChange={(e) => handleInputChange('gender', e.target.value as 'boys' | 'girls' | 'mixed')}
                  className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 ${
                    errors.gender ? 'border-red-300' : 'border-gray-300'
                  }`}
                >
                  <option value="boys">👦 {t('classes.boys')} </option>
                  <option value="girls">👧  {t('classes.girls')}</option>
                  <option value="mixed">👥  {t('classes.mixedClass')}</option>
                </select>
                <p className="mt-1 text-xs text-gray-500">
                  {t('classes.classSpecify')}
                </p>
                {errors.gender && <p className="mt-1 text-sm text-red-600">{errors.gender}</p>}
              </div>

            </div>

            {/* Info Alert */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex">
                <div className="flex-shrink-0">
                  <svg className="h-5 w-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div className="ml-3">
                  <h3 className="text-sm font-medium text-blue-800">{t('classes.createClass.smartCodeGeneration')}</h3>
                  <div className="mt-2 text-sm text-blue-700">
                    <p>
                      {t('classes.createClass.smartCodeDescription')}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-end gap-3 pt-6 border-t border-gray-200">
              <button
                type="button"
                onClick={handleClose}
                disabled={loading}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
                {t('classes.createClass.buttons.cancel')}
              </button>
              <button
                type="submit"
                disabled={loading}
                className="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {loading ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                    {t('classes.createClass.buttons.saving')}
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                    </svg>
                    {editData ? t('classes.createClass.buttons.updateClass') : t('classes.createClass.buttons.createClass')}
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default CreateClassModal;